#include "SevenSegmentDisplayConstants.h"

std::map<char, std::array<uint8, 8>> SYMBOL_TO_SEGMENTS = {{'0', {HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, LOW,  LOW}},
                                                           {'1', {LOW,  HIGH, HIGH, LOW,  LOW,  LOW,  LOW,  LOW}},
                                                           {'2', {HIGH, HIGH, LOW,  HIGH, HIGH, LOW,  HIGH, LOW}},
                                                           {'3', {HIGH, HIGH, HIGH, HIGH, LOW,  LOW,  HIGH, LOW}},
                                                           {'4', {LOW,  HIGH, HIGH, LOW,  LOW,  HIGH, HIGH, LOW}},
                                                           {'5', {HIGH, LOW,  HIGH, HIGH, LOW,  HIGH, HIGH, LOW}},
                                                           {'6', {HIGH, LOW,  HIGH, HIGH, HIGH, HIGH, HIGH, LOW}},
                                                           {'7', {HIGH, HIGH, HIGH, LOW,  LOW,  LOW,  LOW,  LOW}},
                                                           {'8', {HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, LOW}},
                                                           {'9', {HIGH, HIGH, HIGH, HIGH, LOW,  HIGH, HIGH, LOW}},
                                                           {'0' + '.', {HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, LOW,  HIGH}},
                                                           {'1' + '.', {LOW,  HIGH, HIGH, LOW,  LOW,  LOW,  LOW,  HIGH}},
                                                           {'2' + '.', {HIGH, HIGH, LOW,  HIGH, HIGH, LOW,  HIGH, HIGH}},
                                                           {'3' + '.', {HIGH, HIGH, HIGH, HIGH, LOW,  LOW,  HIGH, HIGH}},
                                                           {'4' + '.', {LOW,  HIGH, HIGH, LOW,  LOW,  HIGH, HIGH, HIGH}},
                                                           {'5' + '.', {HIGH, LOW,  HIGH, HIGH, LOW,  HIGH, HIGH, HIGH}},
                                                           {'6' + '.', {HIGH, LOW,  HIGH, HIGH, HIGH, HIGH, HIGH, HIGH}},
                                                           {'7' + '.', {HIGH, HIGH, HIGH, LOW,  LOW,  LOW,  LOW,  HIGH}},
                                                           {'8' + '.', {HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH, HIGH}},
                                                           {'9' + '.', {HIGH, HIGH, HIGH, HIGH, LOW,  HIGH, HIGH, HIGH}},
                                                           {'A', {HIGH, HIGH, HIGH, LOW,  HIGH, HIGH, HIGH, LOW}},
                                                           {'B', {LOW,  LOW,  HIGH, HIGH, HIGH, HIGH, HIGH, LOW}},
                                                           {'C', {HIGH, LOW,  LOW,  HIGH, HIGH, HIGH, LOW,  LOW}},
                                                           {'D', {LOW,  HIGH, HIGH, HIGH, HIGH, LOW,  HIGH, LOW}},
                                                           {'E', {HIGH, LOW,  LOW,  HIGH, HIGH, HIGH, HIGH, LOW}},
                                                           {'F', {HIGH, LOW,  LOW,  LOW,  HIGH, HIGH, HIGH, LOW}},
                                                           {'-', {LOW,  LOW,  LOW,  LOW,  LOW,  LOW,  HIGH, LOW}},
                                                           {'.', {LOW,  LOW,  LOW,  LOW,  LOW,  LOW,  LOW,  HIGH }},
                                                           {0,   {LOW,  LOW,  LOW,  LOW,  LOW,  LOW,  LOW,  LOW}}};
std::map<char, uint8> SYMBOL_TO_SEGMENTS_REGISTER = {{'0', 0b11111100},
                                                     {'1', 0b01100000},
                                                     {'2', 0b11011010},
                                                     {'3', 0b11110010},
                                                     {'4', 0b01100110},
                                                     {'5', 0b10110110},
                                                     {'6', 0b10111110},
                                                     {'7', 0b11100000},
                                                     {'8', 0b11111110},
                                                     {'9', 0b11110110},
                                                     {'0' + '.', 0b11111101},
                                                     {'1' + '.', 0b01100001},
                                                     {'2' + '.', 0b11011011},
                                                     {'3' + '.', 0b11110011},
                                                     {'4' + '.', 0b01100111},
                                                     {'5' + '.', 0b10110111},
                                                     {'6' + '.', 0b10111111},
                                                     {'7' + '.', 0b11100001},
                                                     {'8' + '.', 0b11111111},
                                                     {'9' + '.', 0b11110111},
                                                     {'A', 0b11101110},
                                                     {'B', 0b00111110},
                                                     {'C', 0b10011100},
                                                     {'D', 0b01111010},
                                                     {'E', 0b10011110},
                                                     {'F', 0b10001110},
                                                     {'-', 0b00000010},
                                                     {'.', 0b00000001},
                                                     {0,   0b00000000}};